# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import GRPCServer_pb2 as GRPCServer__pb2


class GRPCServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Register = channel.unary_unary(
        '/GRPCServer.GRPCServer/Register',
        request_serializer=GRPCServer__pb2.User.SerializeToString,
        response_deserializer=GRPCServer__pb2.RegisterResult.FromString,
        )
    self.Login = channel.unary_unary(
        '/GRPCServer.GRPCServer/Login',
        request_serializer=GRPCServer__pb2.User.SerializeToString,
        response_deserializer=GRPCServer__pb2.LoginResult.FromString,
        )
    self.Logout = channel.unary_unary(
        '/GRPCServer.GRPCServer/Logout',
        request_serializer=GRPCServer__pb2.EmptyRequest.SerializeToString,
        response_deserializer=GRPCServer__pb2.StringResponse.FromString,
        )
    self.Share = channel.unary_unary(
        '/GRPCServer.GRPCServer/Share',
        request_serializer=GRPCServer__pb2.ShareRequest.SerializeToString,
        response_deserializer=GRPCServer__pb2.StringResponse.FromString,
        )
    self.CreateFolder = channel.unary_unary(
        '/GRPCServer.GRPCServer/CreateFolder',
        request_serializer=GRPCServer__pb2.PathRequest.SerializeToString,
        response_deserializer=GRPCServer__pb2.StringResponse.FromString,
        )
    self.Rename = channel.unary_unary(
        '/GRPCServer.GRPCServer/Rename',
        request_serializer=GRPCServer__pb2.RenameRequest.SerializeToString,
        response_deserializer=GRPCServer__pb2.StringResponse.FromString,
        )
    self.Delete = channel.unary_unary(
        '/GRPCServer.GRPCServer/Delete',
        request_serializer=GRPCServer__pb2.PathRequest.SerializeToString,
        response_deserializer=GRPCServer__pb2.StringResponse.FromString,
        )
    self.Upload = channel.unary_unary(
        '/GRPCServer.GRPCServer/Upload',
        request_serializer=GRPCServer__pb2.UploadRequest.SerializeToString,
        response_deserializer=GRPCServer__pb2.StringResponse.FromString,
        )
    self.UploadBlock = channel.stream_unary(
        '/GRPCServer.GRPCServer/UploadBlock',
        request_serializer=GRPCServer__pb2.BlockRequest.SerializeToString,
        response_deserializer=GRPCServer__pb2.StringResponse.FromString,
        )
    self.Download = channel.unary_unary(
        '/GRPCServer.GRPCServer/Download',
        request_serializer=GRPCServer__pb2.PathRequest.SerializeToString,
        response_deserializer=GRPCServer__pb2.StringResponse.FromString,
        )
    self.DownloadBlock = channel.stream_unary(
        '/GRPCServer.GRPCServer/DownloadBlock',
        request_serializer=GRPCServer__pb2.BlockRequest.SerializeToString,
        response_deserializer=GRPCServer__pb2.StringResponse.FromString,
        )
    self.GetMetadata = channel.unary_unary(
        '/GRPCServer.GRPCServer/GetMetadata',
        request_serializer=GRPCServer__pb2.PathRequest.SerializeToString,
        response_deserializer=GRPCServer__pb2.StringResponse.FromString,
        )
    self.ListFolder = channel.unary_unary(
        '/GRPCServer.GRPCServer/ListFolder',
        request_serializer=GRPCServer__pb2.PathRequest.SerializeToString,
        response_deserializer=GRPCServer__pb2.StringResponse.FromString,
        )


class GRPCServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Register(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Login(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Logout(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Share(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateFolder(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Rename(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Upload(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UploadBlock(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Download(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DownloadBlock(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMetadata(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListFolder(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GRPCServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Register': grpc.unary_unary_rpc_method_handler(
          servicer.Register,
          request_deserializer=GRPCServer__pb2.User.FromString,
          response_serializer=GRPCServer__pb2.RegisterResult.SerializeToString,
      ),
      'Login': grpc.unary_unary_rpc_method_handler(
          servicer.Login,
          request_deserializer=GRPCServer__pb2.User.FromString,
          response_serializer=GRPCServer__pb2.LoginResult.SerializeToString,
      ),
      'Logout': grpc.unary_unary_rpc_method_handler(
          servicer.Logout,
          request_deserializer=GRPCServer__pb2.EmptyRequest.FromString,
          response_serializer=GRPCServer__pb2.StringResponse.SerializeToString,
      ),
      'Share': grpc.unary_unary_rpc_method_handler(
          servicer.Share,
          request_deserializer=GRPCServer__pb2.ShareRequest.FromString,
          response_serializer=GRPCServer__pb2.StringResponse.SerializeToString,
      ),
      'CreateFolder': grpc.unary_unary_rpc_method_handler(
          servicer.CreateFolder,
          request_deserializer=GRPCServer__pb2.PathRequest.FromString,
          response_serializer=GRPCServer__pb2.StringResponse.SerializeToString,
      ),
      'Rename': grpc.unary_unary_rpc_method_handler(
          servicer.Rename,
          request_deserializer=GRPCServer__pb2.RenameRequest.FromString,
          response_serializer=GRPCServer__pb2.StringResponse.SerializeToString,
      ),
      'Delete': grpc.unary_unary_rpc_method_handler(
          servicer.Delete,
          request_deserializer=GRPCServer__pb2.PathRequest.FromString,
          response_serializer=GRPCServer__pb2.StringResponse.SerializeToString,
      ),
      'Upload': grpc.unary_unary_rpc_method_handler(
          servicer.Upload,
          request_deserializer=GRPCServer__pb2.UploadRequest.FromString,
          response_serializer=GRPCServer__pb2.StringResponse.SerializeToString,
      ),
      'UploadBlock': grpc.stream_unary_rpc_method_handler(
          servicer.UploadBlock,
          request_deserializer=GRPCServer__pb2.BlockRequest.FromString,
          response_serializer=GRPCServer__pb2.StringResponse.SerializeToString,
      ),
      'Download': grpc.unary_unary_rpc_method_handler(
          servicer.Download,
          request_deserializer=GRPCServer__pb2.PathRequest.FromString,
          response_serializer=GRPCServer__pb2.StringResponse.SerializeToString,
      ),
      'DownloadBlock': grpc.stream_unary_rpc_method_handler(
          servicer.DownloadBlock,
          request_deserializer=GRPCServer__pb2.BlockRequest.FromString,
          response_serializer=GRPCServer__pb2.StringResponse.SerializeToString,
      ),
      'GetMetadata': grpc.unary_unary_rpc_method_handler(
          servicer.GetMetadata,
          request_deserializer=GRPCServer__pb2.PathRequest.FromString,
          response_serializer=GRPCServer__pb2.StringResponse.SerializeToString,
      ),
      'ListFolder': grpc.unary_unary_rpc_method_handler(
          servicer.ListFolder,
          request_deserializer=GRPCServer__pb2.PathRequest.FromString,
          response_serializer=GRPCServer__pb2.StringResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'GRPCServer.GRPCServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
