from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_UNDERLINE, WD_COLOR, WD_LINE_SPACING, WD_TAB_ALIGNMENT, WD_TAB_LEADER
from docx.enum.dml import MSO_THEME_COLOR, MSO_COLOR_TYPE

aligns = dict()
aligns[WD_ALIGN_PARAGRAPH.CENTER] = 'center'
aligns[WD_ALIGN_PARAGRAPH.LEFT] = 'left'
aligns[WD_ALIGN_PARAGRAPH.RIGHT] = 'right'
aligns[WD_ALIGN_PARAGRAPH.JUSTIFY] = 'justify'
aligns[WD_ALIGN_PARAGRAPH.DISTRIBUTE] = 'distribute'
aligns[WD_ALIGN_PARAGRAPH.JUSTIFY_MED] = 'justify_med'
aligns[WD_ALIGN_PARAGRAPH.JUSTIFY_HI] = 'justify_hi'
aligns[WD_ALIGN_PARAGRAPH.JUSTIFY_LOW] = 'justify_low'
aligns[WD_ALIGN_PARAGRAPH.THAI_JUSTIFY] = 'thai_justify'

unders = dict()
unders[WD_UNDERLINE.NONE] = 'wd_none'
unders[WD_UNDERLINE.SINGLE] = 'wd_single'
unders[WD_UNDERLINE.WORDS] = 'wd_words'
unders[WD_UNDERLINE.DOUBLE] = 'wd_double'
unders[WD_UNDERLINE.DOTTED] = 'wd_dotted'
unders[WD_UNDERLINE.THICK] = 'wd_thick'
unders[WD_UNDERLINE.DASH] = 'wd_dash'
unders[WD_UNDERLINE.DOT_DASH] = 'wd_dot_dash'
unders[WD_UNDERLINE.DOT_DOT_DASH] = 'wd_dot_dot_dash'
unders[WD_UNDERLINE.WAVY] = 'wd_wavy'
unders[WD_UNDERLINE.DOTTED_HEAVY] = 'wd_dotted_heavy'
unders[WD_UNDERLINE.DASH_HEAVY] = 'wd_dash_heavy'
unders[WD_UNDERLINE.DOT_DASH_HEAVY] = 'wd_dot_dash_heavy'
unders[WD_UNDERLINE.DOT_DOT_DASH_HEAVY] = 'wd_dot_dot_dash_heavy'
unders[WD_UNDERLINE.WAVY_HEAVY] = 'wd_wavy_heavy'
unders[WD_UNDERLINE.DASH_LONG] = 'wd_dash_long'
unders[WD_UNDERLINE.WAVY_DOUBLE] = 'wd_wavy_double'
unders[WD_UNDERLINE.DASH_LONG_HEAVY] = 'wd_dash_long_heavy'

highlights = dict()
highlights[WD_COLOR.AUTO] = 'auto'
highlights[WD_COLOR.BLACK] = 'black'
highlights[WD_COLOR.BLUE] = 'blue'
highlights[WD_COLOR.BRIGHT_GREEN] = 'bright_green'
highlights[WD_COLOR.DARK_BLUE] = 'dark_blue'
highlights[WD_COLOR.DARK_RED] = 'dark_red'
highlights[WD_COLOR.DARK_YELLOW] = 'dark_yellow'
highlights[WD_COLOR.GRAY_25] = 'gray_25'
highlights[WD_COLOR.GRAY_50] = 'gray_50'
highlights[WD_COLOR.GREEN] = 'green'
highlights[WD_COLOR.PINK] = 'pink'
highlights[WD_COLOR.RED] = 'red'
highlights[WD_COLOR.TEAL] = 'teal'
highlights[WD_COLOR.TURQUOISE] = 'turquoise'
highlights[WD_COLOR.VIOLET] = 'violet'
highlights[WD_COLOR.WHITE] = 'white'
highlights[WD_COLOR.YELLOW] = 'yellow'

themecolor = dict()
themecolor[MSO_THEME_COLOR.NOT_THEME_COLOR] = 'not_theme_color'
themecolor[MSO_THEME_COLOR.ACCENT_1] = 'accent_1'
themecolor[MSO_THEME_COLOR.ACCENT_2] = 'accent_2'
themecolor[MSO_THEME_COLOR.ACCENT_3] = 'accent_3'
themecolor[MSO_THEME_COLOR.ACCENT_4] = 'accent_4'
themecolor[MSO_THEME_COLOR.ACCENT_5] = 'accent_5'
themecolor[MSO_THEME_COLOR.ACCENT_6] = 'accent_6'
themecolor[MSO_THEME_COLOR.BACKGROUND_1] = 'background_1'
themecolor[MSO_THEME_COLOR.BACKGROUND_2] = 'background_2'
themecolor[MSO_THEME_COLOR.DARK_1] = 'dark_1'
themecolor[MSO_THEME_COLOR.DARK_2] = 'dark_2'
themecolor[MSO_THEME_COLOR.FOLLOWED_HYPERLINK] = 'followed_hyperlink'
themecolor[MSO_THEME_COLOR.HYPERLINK] = 'hyperlink'
themecolor[MSO_THEME_COLOR.LIGHT_1] = 'light_1'
themecolor[MSO_THEME_COLOR.LIGHT_2] = 'light_2'
themecolor[MSO_THEME_COLOR.TEXT_1] = 'text_1'
themecolor[MSO_THEME_COLOR.TEXT_2] = 'text_2'

colortype = dict()
colortype[MSO_COLOR_TYPE.RGB] = 'rgb'
colortype[MSO_COLOR_TYPE.THEME] = 'theme'
colortype[MSO_COLOR_TYPE.AUTO] = 'auto'

linespacing = dict()
linespacing[WD_LINE_SPACING.ONE_POINT_FIVE] = 'one_point_five'
linespacing[WD_LINE_SPACING.AT_LEAST] = 'at_least'
linespacing[WD_LINE_SPACING.DOUBLE] = 'double'
linespacing[WD_LINE_SPACING.EXACTLY] = 'exactly'
linespacing[WD_LINE_SPACING.MULTIPLE] = 'multiple'
linespacing[WD_LINE_SPACING.SINGLE] = 'single'

tabaligns = dict()
tabaligns[WD_TAB_ALIGNMENT.LEFT] = 'left'
tabaligns[WD_TAB_ALIGNMENT.CENTER] = 'center'
tabaligns[WD_TAB_ALIGNMENT.RIGHT] = 'right'
tabaligns[WD_TAB_ALIGNMENT.DECIMAL] = 'decimal'
tabaligns[WD_TAB_ALIGNMENT.BAR] = 'bar'
tabaligns[WD_TAB_ALIGNMENT.LIST] = 'list'
tabaligns[WD_TAB_ALIGNMENT.CLEAR] = 'clear'
tabaligns[WD_TAB_ALIGNMENT.END] = 'end'
tabaligns[WD_TAB_ALIGNMENT.NUM] = 'num'
tabaligns[WD_TAB_ALIGNMENT.START] = 'start'

leaders = dict()
leaders[WD_TAB_LEADER.SPACES] = 'spaces'
leaders[WD_TAB_LEADER.DOTS] = 'dots'
leaders[WD_TAB_LEADER.DASHES] = 'dashes'
leaders[WD_TAB_LEADER.LINES] = 'lines'
leaders[WD_TAB_LEADER.HEAVY] = 'heavy'
leaders[WD_TAB_LEADER.MIDDLE_DOT] = 'middle_dot'
